// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZ3ZshJQAeRBBMdsiizDKUaWCG26XSKM',
    appId: '1:1021909815248:web:8f2b956a839ecd926273d5',
    messagingSenderId: '1021909815248',
    projectId: 'kurankerimapp',
    authDomain: 'kurankerimapp.firebaseapp.com',
    storageBucket: 'kurankerimapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZyYB8Kjz2ww6CLGkbb2w07eCf2C-sMU',
    appId: '1:1021909815248:android:f7461a57280faf9e6273d5',
    messagingSenderId: '1021909815248',
    projectId: 'kurankerimapp',
    storageBucket: 'kurankerimapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAG5jZgXxv35k0K60RsjgD5bK5e_5bKDE',
    appId: '1:1021909815248:ios:6c41736915a583b76273d5',
    messagingSenderId: '1021909815248',
    projectId: 'kurankerimapp',
    storageBucket: 'kurankerimapp.appspot.com',
    iosClientId: '1021909815248-fpjk06flf31akp4rvhumm3jpnk3b68uv.apps.googleusercontent.com',
    iosBundleId: 'com.sahibulnf.quranApp',
  );
}
